database:
  host: "postgres"
  port: 3306
  user: "postgres"
  password: "postgres"
  db_name: "payments"


nats_streaming:
  host: "localhost"
  port: 4222
  cluster_id: "NATS"
  client_id: "sub-1"
  channel: "channel"


http:
  port: 5000